import pandas as pd
import numpy as np
import statsmodels.api as sm
from statsmodels.tsa.regime_switching.markov_regression import MarkovRegression
from statsmodels.discrete.discrete_model import Logit
import matplotlib.pyplot as plt
import seaborn as sns
import os
from datetime import datetime

# ====================== SETUP ======================
os.makedirs("dashboard", exist_ok=True)

# ====================== LOAD DATA ======================
macro = pd.read_csv("data/macro_data.csv", parse_dates=["date"], index_col="date")
corp = pd.read_csv("data/bellwether_corporate_index.csv", parse_dates=["date"], index_col="date")

df = macro.join(corp, how="outer").dropna()

# Create Bellwether Corporate Index
df["Bellwether_Index"] = df[[
    "WMT_Inv_Growth", "PG_Inv_Growth", "AAPL_Inv_Growth",
    "JPM_Inv_Growth", "CAT_Inv_Growth", "FDX_Inv_Growth",
    "TSLA_Inv_Days", "SPX_Guidance_Revision", "Duke_CFO_Capex"
]].mean(axis=1)

# Standardize predictors
predictors = ["ISM_New_Orders", "Philly_Capex", "UMich_Sentiment", 
              "Bellwether_Index", "Duke_CFO_Capex", "SPX_Guidance_Revision"]

df[predictors] = (df[predictors] - df[predictors].mean()) / df[predictors].std()

for var in predictors + ["GDP_Growth"]:
    df[f"{var}_lag1"] = df[var].shift(1)

df = df.dropna()

# ====================== REGIME-SWITCHING MODEL ======================
endog = df["GDP_Growth"]
exog = df[[f"{v}_lag1" for v in predictors]]

ms_model = MarkovRegression(endog, k_regimes=2, exog=exog, 
                            switching_variance=True, switching_exog=True)
ms_results = ms_model.fit()

df["Regime_Prob_Expansion"] = ms_results.smoothed_marginal_probabilities[0]
df["Regime_Prob_Recession"] = ms_results.smoothed_marginal_probabilities[1]

# ====================== LOGISTIC RECESSION MODEL ======================
logit_exog = sm.add_constant(df[[f"{v}_lag1" for v in predictors] + ["Regime_Prob_Recession_lag1"]])
logit_model = Logit(df["Recession_Next4Q"], logit_exog)
logit_results = logit_model.fit()

df["Recession_Prob"] = logit_results.predict()

# ====================== DASHBOARD ======================
latest = df.iloc[-1]
latest_date = df.index[-1]

# Save plots
fig, axes = plt.subplots(2, 2, figsize=(14, 10))

df[["Regime_Prob_Expansion", "Regime_Prob_Recession"]].plot(ax=axes[0, 0], title="Regime Probabilities")
axes[0, 0].axhline(0.5, color="gray", linestyle="--")

df["Recession_Prob"].plot(ax=axes[0, 1], title="4-Quarter Recession Probability", color="red")

df["Bellwether_Index"].plot(ax=axes[1, 0], label="Bellwether Index", color="blue")
df["GDP_Growth"].plot(ax=axes[1, 0].twinx(), label="GDP Growth", color="green", alpha=0.6)
axes[1, 0].set_title("Bellwether Index vs GDP Growth")

latest_vals = df.loc[latest_date, [f"{v}_lag1" for v in predictors]]
sns.heatmap(latest_vals.to_frame().T, annot=True, cmap="RdYlGn", center=0, 
            ax=axes[1, 1], cbar=False)
axes[1, 1].set_title("Latest Standardized Indicators")

plt.tight_layout()
plt.savefig("dashboard/latest_dashboard.png", dpi=150, bbox_inches="tight")
plt.close()

# Generate HTML Dashboard
html = f"""
<!DOCTYPE html>
<html>
<head>
    <title>Economic Regime Dashboard</title>
    <meta charset="UTF-8">
</head>
<body style="font-family: system-ui, Arial; max-width: 1100px; margin: 40px auto; padding: 20px; line-height: 1.6;">
    <h1>Economic Regime Dashboard</h1>
    <p><strong>Last Updated:</strong> {datetime.now().strftime('%Y-%m-%d %H:%M UTC')}</p>
    
    <h2>Current Regime Probability</h2>
    <p><strong>Expansion:</strong> {latest['Regime_Prob_Expansion']*100:.1f}%</p>
    <p><strong>Recession:</strong> {latest['Regime_Prob_Recession']*100:.1f}%</p>
    
    <h2>4-Quarter Ahead Recession Probability</h2>
    <p style="font-size: 28px; color: #d32f2f; font-weight: bold;">
        {latest['Recession_Prob']*100:.1f}%
    </p>
    
    <h2>Latest Dashboard Visualization</h2>
    <img src="latest_dashboard.png" style="max-width: 100%; border: 1px solid #ddd; border-radius: 8px;">
    
    <h2>Key Leading Indicators (Standardized)</h2>
    <pre style="background: #f5f5f5; padding: 15px; border-radius: 6px;">{latest[[f"{v}_lag1" for v in predictors]].to_string()}</pre>
    
    <footer style="margin-top: 60px; color: #666; font-size: 14px;">
        Auto-generated by GitHub Actions • Updates weekly
    </footer>
</body>
</html>
"""

with open("dashboard/index.html", "w", encoding="utf-8") as f:
    f.write(html)

print("✅ Dashboard successfully generated and saved to /dashboard folder")
